# Generated by Django 2.1.5 on 2019-01-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=256, verbose_name='Власник авто')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='Рік виготовлення')),
                ('brand', models.CharField(choices=[('AU', 'Audi'), ('TY', 'Toyota'), ('TS', 'Tesla'), ('PS', 'Porsche')], max_length=2, verbose_name='Марка авто')),
                ('category', models.CharField(choices=[('1800', 'To 1990'), ('1990', 'From 1990 to 2000'), ('2000', 'From 2000 to 2010'), ('2010', 'From 2000')], max_length=4, verbose_name='категорія по року виготовлення')),
                ('models', models.CharField(choices=[('A6', 'Audi A6'), ('A8', 'Audi A6'), ('Q5', 'Audi Q5'), ('Aristo', 'Toyota Aristo'), ('Camry', 'Touota Camry'), ('ModelX', 'Tesla Model X 100D Premium'), ('Panamera', 'Porshe Panamera'), ('Cayman', 'Pordhe Cayman')], max_length=10, verbose_name='молель авто')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
            },
        ),
    ]
