# Generated by Django 2.1.5 on 2019-01-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('audi_a6', 'Audi A6'), ('audi_a8', 'Audi A8'), ('audi_q5', 'Audi Q5'), ('toyota_aristo', 'Toyota Aristo'), ('toyota_camry', 'Toyota Camry'), ('tesla_model_x', 'Tesla Model X 100D Premium'), ('porshe_panamera', 'Porshe Panamera'), ('porshe_cayman', 'Porshe Cayman')], max_length=20, verbose_name='модель авто'),
        ),
    ]
